eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.31.192:8761/eureka/
server:
  port: 65000
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routs:
      - id: eurekaclient
        uri: lb://EUREKA-CLIENT
        predicates:
        - Path=/yml/**
        filters:
          - StripPrefix=1
management:
  security:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always